[project]
name = "machine-learning"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Bertrand Jayles", email = "bertrand.jayles@gmail.com" }
]
requires-python = ">=3.9"
dependencies = [
    "ipykernel>=6.31.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.9.4",
    "numpy>=2.0.2",
    "pandas>=2.3.3",
    "scikit-learn>=1.6.1",
    "seaborn>=0.13.2",
]

[project.scripts]
machine-learning = "machine_learning:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
